"""add email verified to users

Revision ID: f4c330cf0d38
Revises: 02ef79796530
Create Date: 2026-09-05 20:37:46.093369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c330cf0d38'
down_revision: Union[str, Sequence[str], None] = '02ef79796530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user', 
        sa.Column(
            'email_verified', 
            sa.Boolean(), 
            nullable=False, 
            server_default=sa.false() # i added this
            ))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
